### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mubix** [improsec/ImproHound#1]
Not sure what's going on there, but it's erroring out when I start ImproHound:
![image](https://user-images.githubusercontent.com/679319/140017176-d1c1b7e7-e686-425c-b7fb-d23427737277.png)

**Comment by mubix** [comment]
For reference - Neo4j 4.1.4, apoc-4.1.0.10-all.jar

**Comment by ADNinja** [comment]
Weird, have not seen that one before. I think it could happen if you have a "corrupt" object in your DB. 

Is it confidential data? Else I can try to debug the problem if you send it.

Alternatively, try to clear your DB and upload the data again. I have experienced corrupt/missing data sometimes when I upload the entire zip, but not when I unzip and upload the json files.

Sorry for replying so late, I forgot to subscribe to notifications.. :)
