### ISSUE TITLE
Getting this error when logging to neo db from improhound

### ISSUE THREAD

**Issue by jaredbarez** [improsec/ImproHound#2]
![image](https://user-images.githubusercontent.com/13761356/166700640-36ef8694-9ee0-4d3b-90c9-f5cabd15231f.png)

**Comment by JonasBK** [comment]
Have you added the APOC plugin to Neo4j? Check out _2. Install APOC Neo4j plugin_  under [Install](https://github.com/improsec/ImproHound#install).

**Comment by jaredbarez** [comment]
The thing is I saw that immediately but was hoping of some other error (i.e. on your side), not having to install the plugin. :-)
Thanks for response and developer's time. I currently work in two relatively large tiering model implementations and would like to see if Improhound finds any anomalies there.
